[package]
name = "jage-subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
jage-api = { version = "0.1", path = "../jage-api" }
rand = "0.8.4"
tracing = "0.1.29"
tracing-subscriber = "0.3.4"
