[package]
name = "jage-subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
jage-api = { version = "0.1", path = "../jage-api" }
rand = "0.8.4"
tokio = { version = "1.15.0", features = ["time", "sync"] }
tonic = "0.6.2"
tracing = "0.1.29"
tracing-subscriber = "0.3.4"
