[package]
name = "duo-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.9"
prost = "0.11"
prost-types = "0.11"
tracing-core = "0.1"
serde_json = "1"

[build-dependencies]
tonic-build = "0.9"
