[package]
name = "duo"
version = "0.1.0"
description = "Observability duet: Logging and Tracing"
edition.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
arrow-array = "40"
arrow-schema = "40"
arrow-json = "40"
axum = "0.6"
rand.workspace = true
include_dir = "0.7"
clap = { version = "4", default-features = false, features = ["std", "derive"] }
duo-api.workspace = true
duo-subscriber.workspace = true
parking_lot = { version = "0.12", features = ["send_guard"] }
parquet = { version = "40", features = ["async"] }
serde.workspace = true
serde_json.workspace = true
time = { version = "0.3", features = ["parsing"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
tonic.workspace = true
tower = "0.4"
tower-http = { version = "0.4", features = ["fs"] }
tracing.workspace = true
tracing-subscriber.workspace = true
datafusion = "26"

[dev-dependencies]
rstest = "0.16"
