[package]
name = "jage"
version = "0.1.0"
edition = "2021"

[dependencies]
jage-api = { version = "0.1", path = "../jage-api" }
tokio = { version = "1.15.0", features = ["rt-multi-thread"] }
tonic = "0.6.2"
tracing = "0.1.29"
tracing-subscriber = "0.3.5"
